### PR TITLE
Fix couple floonet loose ends

### LINKED ISSUE #2216: Make genesis coinbase easier to restore and spend
Currently it looks like the restore process gets the derivation wrong, leading the an output being properly detected but then setup with the wrong key.

### PR DESCRIPTION
**Pull request by ignopeverell**
Fixes #2216

/cc @tromp @yeastplume

### CODE REVIEW

File: core/src/core/transaction.rs [hunk 1]
```diff
@@ -1366,20 +1366,12 @@ pub fn kernel_sig_msg(
...
-		BigEndian::write_u64(&mut bytes[24..], lock_height);
-		secp::Message::from_slice(&bytes)?
-	} else {
-		let hash = match features {
-			KernelFeatures::COINBASE => (features).hash(),
-			KernelFeatures::PLAIN => (features, fee).hash(),
-			_ => (features, fee, lock_height).hash(),
-		};
-		secp::Message::from_slice(&hash.as_bytes())?
+	let hash = match features {
```
Comment (mably) [inline core/src/core/transaction.rs]: References to testnet4 in the function description comment should probably be removed as the corresponding code is being removed for the function body.

Comment (ignopeverell) [reply core/src/core/transaction.rs]: Good catch, fixed.
