### PR TITLE
Testnet1 keychain macro use

### LINKED ISSUE #658: store sumtree tests failing randomly
Just saw the following pass 15 times in a row -
`cargo test -p grin_store sumtree`

Then it failed randomly on the next run - 

```
running 4 tests
test sumtree_append ... ok
test sumtree_prune_compact ... FAILED
test sumtree_reload ... FAILED
test sumtree_rewind ... ok

failures:

---- sumtree_prune_compact stdout ----
	thread 'sumtree_prune_compact' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- sumtree_reload stdout ----
	thread 'sumtree_reload' panicked at 'assertion failed: `(left == right)`
  left: `32`,
 right: `16`', store/tests/sumtree.rs:132:4


failures:
    sumtree_prune_compact
    sumtree_reload

test result: FAILED. 2 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out
```

Thanks @mfronczyk for originally reporting this in gitter.

### PR DESCRIPTION
**Pull request by sesam**
[Testnet1] cleanup compiler errors and fix tests concurrency issue for `cargo test -p grin_store sumtree`
- tried but failed to fix `cargo build` complaint about unused #[macro use]. See also 7a803a8
- fix other compiler complaints
- give sumtree tests method-tagged folder names so they don't overwrite each others' files

Fixes #658

### CODE REVIEW

File: keychain/src/lib.rs [hunk 1]
```diff
@@ -19,6 +19,8 @@ extern crate byteorder;
 extern crate grin_util as util;
 extern crate rand;
 extern crate serde;
+// #[allow(unused_imports)]
+#[cfg(test)]
```
Comment (antiochp) [inline keychain/src/lib.rs]: Nice.

Comment (sesam) [reply keychain/src/lib.rs]: I think that commenting it out means it's ignored. On the master branch I made it a bit more clear, but since TravisCI already passed and the testnet1 branch is on a withering milestone I got lazy :)
