### PR TITLE
Externalized all peers selection and handling

### LINKED ISSUE #430: thread 'main' panicked at 'already mutably borrowed: BorrowError' (with backtrace)
This happened on a mid-2015 MacBook pro, with the latest git pull, while syncing from scratch. Got as far as 13477 without the issue #426 occurring even once. 

Log:
Dec 05 07:04:55.326 INFO Updated head to 6967d5ef at 13472.
Dec 05 07:04:55.453 INFO Updated head to a11c6b11 at 13473.
Dec 05 07:04:55.575 INFO Updated head to bd0bca50 at 13474.
Dec 05 07:04:55.714 INFO Updated head to db7f265f at 13475.
Dec 05 07:04:55.854 INFO Updated head to 0cdc4b8b at 13476.
Dec 05 07:04:55.986 INFO Updated head to f55b561f at 13477.
thread 'main' panicked at 'already mutably borrowed: BorrowError', src/libcore/result.rs:860:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_new
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: <core::result::Result<T, E>>::expect
  10: <core::cell::RefCell<T>>::borrow
  11: <grin_util::OneTime<T>>::borrow
  12: grin_grin::adapters::NetToChainAdapter::is_syncing
  13: grin_grin::adapters::NetToChainAdapter::chain_opts
  14: <grin_grin::adapters::NetToChainAdapter as grin_p2p::types::NetAdapter>::block_received
  15: <grin_p2p::peer::TrackingAdapter as grin_p2p::types::NetAdapter>::block_received
  16: grin_p2p::protocol::handle_payload
  17: <grin_p2p::protocol::ProtocolV1 as grin_p2p::types::Protocol>::handle::{{closure}}
  18: <F as grin_p2p::conn::Handler>::handle
  19: grin_p2p::conn::TimeoutConnection::listen::{{closure}}
  20: <F as grin_p2p::conn::Handler>::handle
  21: grin_p2p::conn::Connection::read_msg::{{closure}}::{{closure}}
  22: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::{{closure}}::{{closure}}
  23: <core::result::Result<T, E>>::map
  24: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::{{closure}}
  25: <futures::future::chain::Chain<A, B, C>>::poll
  26: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
  27: <futures::stream::fold::Fold<S, F, Fut, T> as futures::future::Future>::poll
  28: <alloc::boxed::Box<F> as futures::future::Future>::poll
  29: <futures::future::map::Map<A, F> as futures::future::Future>::poll
  30: <futures::future::select::Select<A, B> as futures::future::Future>::poll
  31: <futures::future::map::Map<A, F> as futures::future::Future>::poll
  32: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
  33: <futures::future::select::Select<A, B> as futures::future::Future>::poll
  34: <futures::future::map::Map<A, F> as futures::future::Future>::poll
  35: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
  36: <alloc::boxed::Box<F> as futures::future::Future>::poll
  37: <futures::future::select::Select<A, B> as futures::future::Future>::poll
  38: <futures::future::map::Map<A, F> as futures::future::Future>::poll
  39: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
  40: <alloc::boxed::Box<F> as futures::future::Future>::poll
  41: <futures::future::chain::Chain<A, B, C>>::poll
  42: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
  43: <alloc::boxed::Box<F> as futures::future::Future>::poll
  44: <futures::future::chain::Chain<A, B, C>>::poll
  45: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
  46: <futures::future::chain::Chain<A, B, C>>::poll
  47: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
  48: <futures::future::chain::Chain<A, B, C>>::poll
  49: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
  50: <alloc::boxed::Box<F> as futures::future::Future>::poll
  51: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}
  52: <futures::task_impl::Spawn<T>>::enter::{{closure}}
  53: futures::task_impl::std::set
  54: <futures::task_impl::Spawn<T>>::enter
  55: <futures::task_impl::Spawn<T>>::poll_future_notify
  56: tokio_core::reactor::Core::dispatch_task::{{closure}}
  57: <scoped_tls::ScopedKey<T>>::set
  58: tokio_core::reactor::Core::dispatch_task
  59: tokio_core::reactor::Core::dispatch
  60: tokio_core::reactor::Core::poll
  61: tokio_core::reactor::Core::run
  62: grin_grin::server::Server::start
  63: grin::server_command
  64: grin::main
  65: __rust_maybe_catch_panic
  66: std::rt::lang_start
  67: main

### PR DESCRIPTION
**Pull request by ignopeverell**
Moved handling to the peer map out of the p2p server and into
its own struct. Allowed factoring code from the net adapter and
simplification of some interactions. Also removes the need for
the adapter to reference the p2p server or peers.

Fixes #430, #453 and #456

### CODE REVIEW

**Comment by kargakis** [comment]
> Fixes #430, #453 and #456

FYI, this format does not work with Github, if you want the issues to be automatically closed.

You need:
Fixes #430 
Fixes #453 
Fixes #456

File: grin/src/adapters.rs [hunk 1]
```diff
@@ -1,4 +1,4 @@
-// Copyright 2016 The Grin Developers
+// Copyright 2017 The Grin Developers
```
Comment (kargakis) [inline grin/src/adapters.rs]: Using a range instead of bumping the year feels more appropriate I think.
