### PR TITLE
Fix concurrency issue around peer add and start. Fixes #1585

### LINKED ISSUE #1585: Grin crashes with unwrap on a None value
```
Sep 24 03:17:20.488 DEBG broadcast_compact_block: 125d6d80, 47091659 at 108764, to 4 peers, done.
Sep 24 03:17:20.490 WARN (Server ID: StratumServer) Solution Found for block 108764 - Yay!!!
Sep 24 03:17:20.490 INFO (Server ID: StratumServer) Got share for block: hash 125d6d80, height 108764, nonce 5060267201443065681, difficulty 377/282, submitted by white
Sep 24 03:17:20.602 DEBG Client 95.216.163.175:13414 connection lost: Connection(Custom { kind: ConnectionAborted, error: StringError("read_exact") })
Sep 24 03:17:20.781 DEBG monitor_peers: on 0.0.0.0:13414, 3 connected (3 most_work). all 594 = 4 healthy + 0 banned + 590 defunct
Sep 24 03:17:20.782 DEBG clean_peers V4(95.216.163.175:13414), not connected
Sep 24 03:17:20.783 DEBG monitor_peers: 0.0.0.0:13414 ask 198.245.50.26:13414 for more peers
Sep 24 03:17:20.784 DEBG Asking 198.245.50.26:13414 for more peers.
Sep 24 03:17:20.785 DEBG monitor_peers: 0.0.0.0:13414 ask 109.74.202.16:13414 for more peers
Sep 24 03:17:20.785 DEBG Asking 109.74.202.16:13414 for more peers.
Sep 24 03:17:20.785 DEBG monitor_peers: 0.0.0.0:13414 ask 8.6.8.66:13414 for more peers
Sep 24 03:17:20.785 DEBG Asking 8.6.8.66:13414 for more peers.
Sep 24 03:17:20.785 DEBG monitor_peers: no preferred peers
Sep 24 03:17:20.785 DEBG monitor_peers: on 0.0.0.0:13414, queue to soon try 95.216.163.175:13414
Sep 24 03:17:21.001 DEBG Connected! Cumulative 40605549 offered from V4(95.216.163.175:13414) "MW/Grin 0.3.0" FULL_HIST | TXHASHSET_HIST | PEER_LIST | FAST_SYNC_NODE | FULL_NODE
Sep 24 03:17:21.002 DEBG Saving newly connected peer 95.216.163.175:13414.
Sep 24 03:17:21.003 DEBG save_peer: V4(95.216.163.175:13414) marked Healthy
Sep 24 03:17:21.005 DEBG Asking 95.216.163.175:13414 for more peers.
Sep 24 03:17:21.101 DEBG get_coinbase: BlockFees { fees: 0, height: 108765, key_id: Some(Identifier(a3df7f5bd87ef1dfce7a)) }
Sep 24 03:17:21.102 DEBG lru_verifier_cache: rangeproofs: 1, not cached (must verify): 1
Sep 24 03:17:21.106 DEBG lru_verifier_cache: kernel sigs: 1, not cached (must verify): 1
Sep 24 03:17:21.109 DEBG Built new block with 0 inputs and 1 outputs, network difficulty: 282, cumulative difficulty 47091941
Sep 24 03:17:21.110 DEBG (Server ID: StratumServer) sending block 108765 with id 0 to stratum clients
Sep 24 03:17:26.173 INFO (Server ID: StratumServer) Got share for block: hash 67027123, height 108765, nonce 16113152869612639768, difficulty 58/282, submitted by white
Sep 24 03:17:30.258 DEBG Received block header 073dc630 at 108764 from 8.6.8.66:13414, going to process.
Sep 24 03:17:30.259 DEBG pipe: process_block_header at 108764 [073dc630]
Sep 24 03:17:30.260 DEBG Requesting compact block 073dc630 from 8.6.8.66:13414
Sep 24 03:17:30.324 DEBG handle_payload: received block: msg_len: 1260
Sep 24 03:17:30.325 DEBG Received block 073dc630 at 108764 from 8.6.8.66:13414, inputs: 0, outputs: 1, kernels: 1, going to process.
Sep 24 03:17:30.326 DEBG pipe: process_block 073dc630 at 108764 with 0 inputs, 1 outputs, 1 kernels
Sep 24 03:17:30.326 DEBG lru_verifier_cache: rangeproofs: 1, not cached (must verify): 1
Sep 24 03:17:30.332 DEBG lru_verifier_cache: kernel sigs: 1, not cached (must verify): 1
Sep 24 03:17:30.338 DEBG adapter: block_accepted: 073dc630
Sep 24 03:17:30.339 DEBG Send header 073dc630 to 198.245.50.26:13414
Sep 24 03:17:30.340 DEBG Send header 073dc630 to 109.74.202.16:13414
Sep 24 03:17:30.341 DEBG Send header 073dc630 to 95.216.163.175:13414
Sep 24 03:17:30.458 DEBG Client 95.216.163.175:13414 connection lost: Connection(Custom { kind: ConnectionAborted, error: StringError("read_exact") })
Sep 24 03:17:36.600 DEBG get_coinbase: BlockFees { fees: 0, height: 108765, key_id: Some(Identifier(a3df7f5bd87ef1dfce7a)) }
Sep 24 03:17:36.601 DEBG lru_verifier_cache: rangeproofs: 1, not cached (must verify): 0
Sep 24 03:17:36.602 DEBG lru_verifier_cache: kernel sigs: 1, not cached (must verify): 1
Sep 24 03:17:36.604 DEBG Built new block with 0 inputs and 1 outputs, network difficulty: 282, cumulative difficulty 47091941
Sep 24 03:17:36.605 DEBG (Server ID: StratumServer) sending block 108765 with id 1 to stratum clients
Sep 24 03:17:40.784 DEBG monitor_peers: on 0.0.0.0:13414, 3 connected (3 most_work). all 594 = 4 healthy + 0 banned + 590 defunct
Sep 24 03:17:40.785 DEBG clean_peers V4(95.216.163.175:13414), not connected
Sep 24 03:17:40.786 DEBG monitor_peers: 0.0.0.0:13414 ask 109.74.202.16:13414 for more peers
Sep 24 03:17:40.787 DEBG Asking 109.74.202.16:13414 for more peers.
Sep 24 03:17:40.788 DEBG monitor_peers: 0.0.0.0:13414 ask 8.6.8.66:13414 for more peers
Sep 24 03:17:40.789 DEBG Asking 8.6.8.66:13414 for more peers.
Sep 24 03:17:40.789 DEBG monitor_peers: 0.0.0.0:13414 ask 198.245.50.26:13414 for more peers
Sep 24 03:17:40.789 DEBG Asking 198.245.50.26:13414 for more peers.
Sep 24 03:17:40.789 DEBG monitor_peers: no preferred peers
Sep 24 03:17:40.789 DEBG monitor_peers: on 0.0.0.0:13414, queue to soon try 95.216.163.175:13414
Sep 24 03:17:41.005 DEBG Connected! Cumulative 40605549 offered from V4(95.216.163.175:13414) "MW/Grin 0.3.0" FULL_HIST | TXHASHSET_HIST | PEER_LIST | FAST_SYNC_NODE | FULL_NODE
Sep 24 03:17:41.006 DEBG Saving newly connected peer 95.216.163.175:13414.
Sep 24 03:17:41.007 DEBG save_peer: V4(95.216.163.175:13414) marked Healthy
Sep 24 03:17:41.080 ERRO 
thread 'sync' panicked at 'called `Option::unwrap()` on a `None` value': libcore/option.rs:345stack backtrace:
   0:     0x560e6d60de1c - backtrace::backtrace::trace::haeeda11cb0a18d0d
   1:     0x560e6d60cdd2 - <backtrace::capture::Backtrace as core::default::Default>::default::h58375e4d637b5237
   2:     0x560e6d60ce48 - backtrace::capture::Backtrace::new::h77ff1d6eb80d3fec
   3:     0x560e6d5a5b2e - grin_util::logger::send_panic_to_log::{{closure}}::hb080dc8158128e7a
   4:     0x560e6d71adf3 - std::panicking::rust_panic_with_hook::he4c3a67f6258a8f9
                        at libstd/panicking.rs:515
   5:     0x560e6d71ab49 - std::panicking::continue_panic_fmt::h156c04b2aea348c7
                        at libstd/panicking.rs:426
   6:     0x560e6d71a865 - rust_begin_unwind
                        at libstd/panicking.rs:337
   7:     0x560e6d7783fb - core::panicking::panic_fmt::h0e6d5c6fb2a34dd6
                        at libcore/panicking.rs:92
   8:     0x560e6d77832a - core::panicking::panic::hfbb77505dc622acd
                        at libcore/panicking.rs:53
   9:     0x560e6d457803 - grin_p2p::peer::Peer::is_connected::hf0eaaab5ea597898
  10:     0x560e6d48dd64 - <core::iter::Cloned<I> as core::iter::iterator::Iterator>::next::hd63e66a68b97b163
  11:     0x560e6d48c228 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter::ha6eaef685cdbdb48
  12:     0x560e6d467f97 - grin_p2p::peers::Peers::connected_peers::h4b3aed308854efe3
  13:     0x560e6d468bb9 - grin_p2p::peers::Peers::most_work_peers::he5d1b341c4d3bb70
  14:     0x560e6d468e5c - grin_p2p::peers::Peers::most_work_peer::h21eaa649cad20f0f
  15:     0x560e6d23ed49 - grin_servers::grin::sync::needs_syncing::hb928963c7742d445
  16:     0x560e6d1ad76f - std::sys_common::backtrace::__rust_begin_short_backtrace::h9a2f3d587e4e8cb7
  17:     0x560e6d203b84 - std::panicking::try::do_call::hb6f1fd8f38e7f518
  18:     0x560e6d73ff89 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  19:     0x560e6d2072f4 - <F as alloc::boxed::FnBox<A>>::call_box::h72eb92d01528792f
  20:     0x560e6d71823a - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output=R> + 'a> as core::ops::function::FnOnce<A>>::call_once::h75e539106a648d39
                        at /checkout/src/liballoc/boxed.rs:650
                         - std::sys_common::thread::start_thread::h88a639c99862a9f5
                        at libstd/sys_common/thread.rs:24
  21:     0x560e6d71b8a5 - std::sys::unix::thread::Thread::new::thread_start::h7d7a420a78cfa84d
                        at libstd/sys/unix/thread.rs:90
  22:     0x7f834fbc66b9 - start_thread
  23:     0x7f834f6e641c - clone
  24:                0x0 - <unknown>


Sep 24 03:17:41.086 DEBG Asking 95.216.163.175:13414 for more peers.
Sep 24 03:17:41.201 ERRO 
thread 'peer' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"': libcore/result.rs:945stack backtrace:
   0:     0x560e6d60de1c - backtrace::backtrace::trace::haeeda11cb0a18d0d
   1:     0x560e6d60cdd2 - <backtrace::capture::Backtrace as core::default::Default>::default::h58375e4d637b5237
   2:     0x560e6d60ce48 - backtrace::capture::Backtrace::new::h77ff1d6eb80d3fec
   3:     0x560e6d5a5b2e - grin_util::logger::send_panic_to_log::{{closure}}::hb080dc8158128e7a
   4:     0x560e6d71adf3 - std::panicking::rust_panic_with_hook::he4c3a67f6258a8f9
                        at libstd/panicking.rs:515
   5:     0x560e6d71ab49 - std::panicking::continue_panic_fmt::h156c04b2aea348c7
                        at libstd/panicking.rs:426
   6:     0x560e6d71a865 - rust_begin_unwind
                        at libstd/panicking.rs:337
   7:     0x560e6d7783fb - core::panicking::panic_fmt::h0e6d5c6fb2a34dd6
                        at libcore/panicking.rs:92
   8:     0x560e6d47489d - core::result::unwrap_failed::h0da2f30cbd388380
   9:     0x560e6d457985 - grin_p2p::peer::Peer::is_banned::he5bdf82459057295
  10:     0x560e6d46d492 - <grin_p2p::peers::Peers as grin_p2p::types::NetAdapter>::is_banned::h52e53f60776d8377
  11:     0x560e6d459d41 - <grin_p2p::peer::TrackingAdapter as grin_p2p::types::NetAdapter>::is_banned::h6f450ca740e71c49
  12:     0x560e6d491916 - <grin_p2p::protocol::Protocol as grin_p2p::conn::MessageHandler>::consume::hf99a31fdb0740981
  13:     0x560e6d4619c3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1bde35303db8c65a
  14:     0x560e6d462ea8 - std::panicking::try::do_call::h39bcc203a7fada48
  15:     0x560e6d73ff89 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  16:     0x560e6d479295 - <F as alloc::boxed::FnBox<A>>::call_box::h1c7ce09c7d72ded3
  17:     0x560e6d71823a - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output=R> + 'a> as core::ops::function::FnOnce<A>>::call_once::h75e539106a648d39
                        at /checkout/src/liballoc/boxed.rs:650
                         - std::sys_common::thread::start_thread::h88a639c99862a9f5
                        at libstd/sys_common/thread.rs:24
  18:     0x560e6d71b8a5 - std::sys::unix::thread::Thread::new::thread_start::h7d7a420a78cfa84d
                        at libstd/sys/unix/thread.rs:90
  19:     0x7f834fbc66b9 - start_thread
  20:     0x7f834f6e641c - clone
  21:                0x0 - <unknown>

```

### PR DESCRIPTION
**Pull request by ignopeverell**
We used to add the peer to the peers list _and then_ start it and set its connection. This leads to peers getting picked up for other tasks (like sync) even though they're not yet fully ready.

### CODE REVIEW

File: p2p/src/peers.rs [hunk 1]
```diff
@@ -56,25 +56,29 @@ impl Peers {
...
-			user_agent: p.info.user_agent.clone(),
-			flags: State::Healthy,
-			last_banned: 0,
-			ban_reason: ReasonForBan::None,
-		};
+	pub fn add_connected(&self, peer: Arc<RwLock<Peer>>) -> Result<(), Error> {
+		let peer_data: PeerData;
+		let addr: SocketAddr;
+		{
+			let p = peer.write().unwrap();
```
Comment (garyyu) [inline p2p/src/peers.rs]: Is it a `read` lock instead of a `write()` lock?

Comment (ignopeverell) [reply p2p/src/peers.rs]: Absolutely right! Fixed now.
