### PR TITLE
Fix 658 and compiler complaints

### LINKED ISSUE #658: store sumtree tests failing randomly
Just saw the following pass 15 times in a row -
`cargo test -p grin_store sumtree`

Then it failed randomly on the next run - 

```
running 4 tests
test sumtree_append ... ok
test sumtree_prune_compact ... FAILED
test sumtree_reload ... FAILED
test sumtree_rewind ... ok

failures:

---- sumtree_prune_compact stdout ----
	thread 'sumtree_prune_compact' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- sumtree_reload stdout ----
	thread 'sumtree_reload' panicked at 'assertion failed: `(left == right)`
  left: `32`,
 right: `16`', store/tests/sumtree.rs:132:4


failures:
    sumtree_prune_compact
    sumtree_reload

test result: FAILED. 2 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out
```

Thanks @mfronczyk for originally reporting this in gitter.

### PR DESCRIPTION
**Pull request by sesam**
Fix tests concurrency issue for `cargo test -p grin_store sumtree` by ensuring these test have method-tagged folder names so they don't overwrite each others' files
Fixes #658

Cleanup compiler errors

### CODE REVIEW

File: pool/src/lib.rs [hunk 1]
```diff
@@ -32,7 +32,8 @@ extern crate grin_keychain as keychain;
 extern crate grin_util as util;
 extern crate rand;
 extern crate serde;
-#[macro_use]
+#[allow(unused_imports)]
+#[macro_use] // Needed for Serialize/Deserialize. The compiler complaining here is a bug.
```
Comment (antiochp) [inline pool/src/lib.rs]: Can we do the `#[cfg(test)]` trick here?

Comment (sesam) [reply pool/src/lib.rs]: No, Serialize/Deserialize is used in a --release build, and I couldn't come up with any combination of allow(unused_imports) and/or cfg[test] to silence the compiler complaints here -- that's why the commit message is "Tried but failed" and then hoping that not all of us (maybe repeatedly) will loose time fighting that particular warning for this particular lib. I think I tried fixing this once before, but found no commits to jog my memory...

**Comment by ignopeverell** [comment]
Ok then. Looks good to me, thanks!
