### PR TITLE
Fix kernel history verification

### LINKED ISSUE #1207: txhashset validation failing on testnet3 branch
Fast-sync appears to be failing currently on `testnet3`.

We see a `StoreErr(NotFoundErr, "wrapped")` in the logs so I suspect something got clobbered with all the PR merges going on.

```
Jun 28 21:03:47.811 DEBG Header head before txhashset request: 83 / 4bbcf88a
Jun 28 21:03:47.811 DEBG Asking 127.0.0.1:13414 for txhashset archive at 64 8a3379a6.
Jun 28 21:03:47.880 DEBG handle_payload: txhashset archive for 8a3379a6 at 64 rewind to 152/138
Jun 28 21:03:47.903 DEBG leaf_set: copying rewound file .grin/txhashset/output/pmmr_leaf.bin.8a3379a6 to .grin/txhashset/output/pmmr_leaf.bin
Jun 28 21:03:47.904 DEBG leaf_set: copying rewound file .grin/txhashset/rangeproof/pmmr_leaf.bin.8a3379a6 to .grin/txhashset/rangeproof/pmmr_leaf.bin
Jun 28 21:03:47.910 DEBG txhashset: validated the output|rproof|kernel mmrs, took 0s
Jun 28 21:03:48.050 DEBG txhashset: verified 71 kernel signatures, pmmr size 138, took 0s
Jun 28 21:03:52.312 DEBG txhashset: verified 33 rangeproofs, pmmr size 152, took 4s
Jun 28 21:03:52.313 DEBG Error returned, discarding txhashset extension: StoreErr(NotFoundErr, "wrapped")
Jun 28 21:03:52.314 ERRO Failed to save txhashset archive: StoreErr(NotFoundErr, "wrapped")
Jun 28 21:03:52.314 DEBG handle_payload: txhashset archive for 8a3379a6 at 64, DONE
```

Have not had time to investigate but it appears to be happening somewhere in the txhashset validation step.

### PR DESCRIPTION
**Pull request by ignopeverell**
Only rewind kernels to avoid requiring proper bitmap extraction.
Also avoids maintaining bitmap data for kernels by introducing a
"prunable" flag on PMMR backend. Finally, clean up some testnet2
migration code.

Fixes #1207. Related to #1214.

### CODE REVIEW

**Comment by yeastplume** [comment]
Cool, makes more sense than the bool flags on rewind

File: store/src/pmmr.rs [hunk 1]
```diff
@@ -218,60 +224,30 @@ where
...
-				let total_shift = prune_list.get_total_shift();
-				let record_len = 32;
-				let sz = hash_file.size()?;
-				sz / record_len + total_shift
-			};
-
-			migrate_rm_log(&mut leaf_set, &rm_log, &prune_list, last_pos)?;
-		}
+		let prune_list = PruneList::open(format!("{}/{}", data_dir, PMMR_PRUN_FILE))?;
+		let leaf_set = LeafSet::open(leaf_set_path.clone())?;
```
Comment (antiochp) [inline store/src/pmmr.rs]: Thanks for cleaning the "migration" code up here!

File: store/src/pmmr.rs [hunk 2]
```diff
@@ -57,6 +57,7 @@ where
 	T: PMMRable,
 {
 	data_dir: String,
+	prunable: bool,
```
Comment (antiochp) [inline store/src/pmmr.rs]: :+1:

I suspect we can take advantage of this `prunable` bool in a subsequent PR and eliminate the `pmmr_leaf.bin` and `pmmr_prun.bin` files completely.

Comment (ignopeverell) [reply store/src/pmmr.rs]: I suspect so too, or maybe layer the pruning part of the PMMR backend on top of the regular one.
